@startuml FactoryMethodClassDiagram.png
skinparam shadowing false

package framework {

	abstract class Product {
		+ {abstract} method1()
		+ {abstract} method2()
		+ {abstract} method3()
	}

	abstract class Creator {
		+ create() : Product
		# {abstract} factoryMethod()
	}

	Creator - Product : Creates >
}

package concretepackage {

	class ConcreteProduct {
		+ method1()
		+ method2()
		+ method3()
	}

	class ConcreteCreator {
		# factoryMethod()
	}

	ConcreteCreator - ConcreteProduct : Creates >
}

Creator <|-d- ConcreteCreator
Product <|-d- ConcreteProduct

@enduml